# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d6b988f6da5ebaef1b15cc9c9a1b490fbaf55014d7cb8829249a365a36d9f3791d49960ea38c292eff5dca959e5e61bd58edd22f502d5dd50537e01dcd0b749d

test:
  secret_key_base: 65f6c9aee0132e7c8c48ac09c90ca4914cea693bf9cd90807566b0c3b47a3d28d832c4eb79ee89ba89b63107097e9d4a1151a36453e2ef3bc795dbd6b21b5c14

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
